<?php
// $Id$

/**
 * @file
 * SMS Panel UI hooks implementations and helper functions.
 */

/**
 * Implementation of hook_menu().
 */
function sms_panel_ui_menu() {
  $items = array();
  
  $items['admin/smsframework/panel'] = array(
    'title' => 'SMS Management Panel',
    'description' => 'Central control panel for managing SMS messages.',
    'access arguments' => array('administer sms panel'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['admin/smsframework/panel/dashboard'] = array(
    'title' => 'Dashboard',
    'description' => 'Overall of site SMS messagings.',
#    'page callback' => 'sms_panel_ui_page_dashboard',
    'access arguments' => array('administer sms panel'),
    'file' => 'sms_panel_ui.inc',
    'weight' => 0,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  // TODO: REVIEW!
  $items['admin/smsframework/panel/sms/%sms'] = array(
    'title callback' => 'sms_title',
    'title argument' => array(4),
    'page callback' => 'sms_panel_ui_page_sms',
    'page arguments' => array(4),
    'access arguments' => array('view sms message'),
    'file' => 'sms_panel_ui.inc',
    'type' => MENU_CALLBACK,
  );
  
  $items['admin/smsframework/panel/sms/%sms/view'] = array(
    'title' => 'View',
    'weight' => 0,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  $items['admin/smsframework/panel/sms/%sms/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sms_panel_ui_sms_delete_confirm', 4),
    'access arguments' => array('delete sms message'),
    'file' => 'sms_panel_ui.inc',
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * Implementation of hook_theme().
 */
#function sms_panel_ui_theme($existing, $type, $theme, $path) {
#  
#}

/**
 * Helper function to return a SMS message URL.
 *
 * @param $sid
 *   SMS identifier or object.
 * @param $type
 *   SMS URL type.
 *
 * @return
 *   The SMS message URL.
 */
function sms_url($sid, $type = 'admin') {
  if (is_object($sid)) {
    $sid = $sid->sid;
  }
  
  switch ($type) {
    case 'admin':
      return 'admin/smsframework/panel/sms/' . $sid;
  }
}

