<?php
// $Id$

/**
 * @file
 * SMS Panel UI hooks implementations and helper functions.
 */

/**
 * Implementation of hook_menu().
 */
function sms_panel_ui_menu() {
  $items = array();
  
  $items['admin/smsframework/panel'] = array(
    'title' => 'SMS Management Panel',
    'description' => 'Central control panel for managing SMS messages.',
    'access arguments' => array('administer sms panel'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['admin/smsframework/panel/dashboard'] = array(
    'title' => 'Dashboard',
    'description' => 'Overall of site SMS messagings.',
    'page_callback' => 'sms_panel_ui_page_dashboard',
    'access arguments' => array('administer sms panel'),
    'file' => 'sms_panel_ui.pages.inc',    
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  
  $items['admin/smsframework/panel/outgoing'] = array(
    'title' => 'Outgoing',
    'description' => 'Keep track of sent SMS messages.',
    'page_callback' => 'sms_panel_ui_page_outgoing',
    'access arguments' => array('view outgoing message logs'),
    'file path' => drupal_get_path('drupal', 'sms_panel_ui'),
    'file' => 'sms_panel_ui.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );
  
  $items['admin/smsframework/panel/incoming'] = array(
    'title' => 'Incoming',
    'description' => 'Keep track of recieved SMS messages.',
    'page_callback' => 'sms_panel_ui_page_incoming',
    'access arguments' => array('view incoming message logs'),
    'file path' => drupal_get_path('drupal', 'sms_panel_ui'),
    'file' => 'sms_panel_ui.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
  );
  
  return $items;
}

