<?php
// $Id$

/**
 * @file
 * SMS Panel Views API hooks implementations.
 */

/**
 * Implements hook_views_api().
 */
function sms_panel_views_views_api() {
  return array(
    'api' => 2.0,
    'path' => drupal_get_path('module', 'sms_panel_views') . '/views',
  );
}

/**
 * Implements hook_form_alter().
 *
 * Adds a messy reset button to Views exposed forms.
 */
function sms_panel_views_form_alter(&$form, $form_state, $form_id) {
  $views_to_alter = array(
    'sms_panel_incoming',
    'sms_panel_outgoing',
  );

  if (in_array($form_state['view']->name, $views_to_alter)) {
    $current_display = $form_state['view']->current_display;
    $reset = array(
      '#type' => 'markup',
      '#value' => '<input '. drupal_attributes(array('type' => 'button', 'value' => t('Reset') )) .
        'class="form-submit" onClick="window.location = \'' .
        url($form_state['view']->display[$current_display]->display_options['path']) . '\';" />',
    );

    // Check wrapper fielset.
    if ($form[$form_id . '_fieldset']) {
     $form[$form_id . '_fieldset']['reset'] = $reset;
    }
    else {
      $form['reset'] = $reset;
    }
  }
}

