<?php
// $Id$

/**
 * @file
 * SMS Panel UI Datepicker hook implementations.
 */

/**
 * Implementation of hook_form_alter().
 */
function sms_panel_ui_datepicker_form_alter(&$form, $form_state, $form_id) {
  $views_to_alter = array(
    'sms_panel_incoming',
    'sms_panel_outgoing',
  );
  
  // Include the datepicker widget.
  if (in_array($form_state['view']->name, $views_to_alter)) {
    // TODO: Make datepicker skins customizable via the UI.
    drupal_add_css(drupal_get_path('module', 'sms_panel_ui_datepicker') . '/css/sms-panel-ui.datepicker.css', 'module');
    
    // TODO: Build the UI and make these all configurable.
    $date_range = variable_get('sms_panel_ui_datepicker_year_range', 3);
    $date_format = variable_get('sms_panel_ui_datepicker_date_format', 'Y-m-d H:i:s');
    foreach ($form as $key => $value) {
      if (strpos($key, 'timestamp') === FALSE) {
        continue;
      }
      
      $form[$key]['#type'] = 'date_popup';
      $form[$key]['#date_format'] = $date_format;
      $form[$key]['#date_year_range'] = '-' . $date_range . ':+' . $date_range;
      
      // Unset unnecessary field options.
      unset($form[$key]['#maxlength']);
      unset($form[$key]['#description']);
    }
  }
}

